### ISSUE TITLE
Wrong file opens (Introduction 3)

### ISSUE THREAD

**Issue by felixkoerber** [aylinsgl/Python_For_Psychologists_23-24#1]
When clicking on introduction 3, on occasion, the old file "introduction_3.md" opens instead of "introduction_3_new.md".

Steps for replication:
1. Click on "Running experiments in python"
2. Click on "Introduction 3"
expected behavior:  introduction_3_new.md opens
behavior: introduction_3.md opens

I do think this is because already built pages (that you did not edit yet for this course) still incorporate an old ToC, maybe because old files are not rebuilt again. Deleting and rebuilding the HTML build might help. Thank you!

**Comment by aylinsgl** [comment]
ugh thats annoying, good catch! It seems like it really only happened when expanding the TOC and then selecting the page, not when clicking on "introduction" and then on the page... It's working for me now, let me know if you run into issues again!
